(function () {
  const C = window.COURSE;
  const chapterIndex = Number(document.body.dataset.chapter || 0);
  const chapter = C.chapters[chapterIndex];
  const params = new URLSearchParams(location.search);
  let lang = params.get('lang') || localStorage.getItem('layout-course-lang') || 'zh';
  if (!['zh', 'en'].includes(lang)) lang = 'zh';
  let activeSection = 0;
  const tx = value => typeof value === 'string' ? value : value[lang];
  const esc = text => String(text).replace(/[&<>]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
  const linkFor = href => `${href}${href.includes('?') ? '&' : '?'}lang=${lang}`;
  const moduleNames = {
    chart:{zh:'每周活跃趋势',en:'Weekly activity'}, active:{zh:'今日活跃',en:'Active today'}, complete:{zh:'完成率',en:'Completion'},
    ranking:{zh:'课程排行',en:'Course ranking'}, recent:{zh:'最近活动',en:'Recent activity'}, device:{zh:'设备分布',en:'Device mix'}
  };
  const nameOf = id => tx(moduleNames[id]);

  const CODE = {
    audit: [`const issues = d3.group(observations, d => d.type);\n\nissueLayer.selectAll("g.issue")\n  .data(issues, d => d[0])\n  .join("g")\n  .attr("class", "issue");`, `const coverage = d3.mean(ISSUE_TYPES, type =>\n  selected.has(type) ? 1 : 0\n);\n\nscoreScale.domain([0, 1]);`],
    matrix: [`const x = d3.scaleLinear().domain([1, 5]).range([54, width - 30]);\nconst y = d3.scaleLinear().domain([1, 5]).range([height - 42, 24]);`, `const drag = d3.drag().on("drag", (event, d) => {\n  d.frequency = x.invert(event.x);\n  d.impact = y.invert(event.y);\n  updatePriority();\n});`],
    hierarchy: [`const size = d3.scaleLinear()\n  .domain([1, 5])\n  .range([1, 4]);\n\nmodules.forEach(d => d.span = size(d.importance));`, `cards.data(layout, d => d.id)\n  .join(enter => enter.append("g"))\n  .transition().duration(500)\n  .attr("transform", d => \`translate(\${d.x},\${d.y})\`);`],
    path: [`const salience = d3.sum([\n  areaWeight(d), positionWeight(d),\n  contrastWeight(d), whitespaceWeight(d)\n]);`, `const ordered = [...modules].sort((a,b) => b.salience - a.salience);\nconst path = d3.line().curve(d3.curveCatmullRom.alpha(.4));`],
    grid: [`const x = d3.scaleBand()\n  .domain(d3.range(columns))\n  .range([margin, width - margin])\n  .paddingInner(gutterRatio);`, `cards.data(layout, d => d.id)\n  .join("g")\n  .transition().duration(600)\n  .attr("transform", d => \`translate(\${x(d.col)},\${d.y})\`);`],
    alignment: [`const nearest = value => gridLines.reduce((a,b) =>\n  Math.abs(b - value) < Math.abs(a - value) ? b : a\n);`, `const error = Math.abs(card.x - nearest(card.x));\ncard.x = nearest(card.x);\nselection.transition().duration(650).attr("transform", position);`],
    ratio: [`const split = d3.scaleLinear().domain([45, 80]).range([0, innerWidth]);\nconst mainWidth = split(mainPercent);\nconst sideWidth = innerWidth - mainWidth - gutter;`, `const readable = lineLength >= 45 && lineLength <= 75;\nfeedback.attr("fill", readable ? success : warning);`],
    rhythm: [`const space = d3.scaleOrdinal()\n  .domain(["xs","sm","md","lg","xl"])\n  .range([1,2,3,5,8].map(n => n * base));`, `rows.data(items, d => d.id).join("g")\n  .transition().duration(450)\n  .attr("transform", (_,i) => \`translate(0,\${i * space("xl")})\`);`],
    proximity: [`const x = d3.scalePoint()\n  .domain(items.map(d => d.id))\n  .range([start, end])\n  .padding(.5);`, `const perceptualGap = betweenGap / insideGap;\nconst grouped = perceptualGap >= 2;\nregions.attr("opacity", grouped ? 1 : .15);`],
    region: [`const groups = d3.groups(items, d => d.group);\nconst hulls = groups.map(([key, values]) => ({ key, bounds: extent(values) }));`, `regionLayer.selectAll("rect")\n  .data(hulls, d => d.key)\n  .join("rect")\n  .transition().attr("opacity", commonRegion ? 1 : 0);`],
    density: [`const padding = d3.scaleLinear().domain([0, 100]).range([6, 28]);\nconst cardGap = padding(breathingRoom);`, `const crowding = d3.mean(cards, d => Math.min(1, d.content / d.area));\nconst scanCost = cards.length * averageDistance(cards);`],
    composition: [`const layouts = { article: articleLayout, dashboard: dashboardLayout, form: formLayout };\nconst layout = layouts[mode](modules, width);`, `modulesG.data(layout, d => d.id).join("g")\n  .transition().duration(650)\n  .attr("transform", d => \`translate(\${d.x},\${d.y})\`);`],
    responsive: [`const mode = width < 560 ? "mobile" : width < 920 ? "tablet" : "desktop";\nconst layout = layoutByMode(mode, modules);`, `cards.data(layout, d => d.id).join("g")\n  .transition().duration(420)\n  .attr("transform", d => \`translate(\${d.x},\${d.y})\`);`],
    priority: [`const visible = modules\n  .filter(d => width > d.minWidth || d.priority >= 4)\n  .sort((a,b) => b.priority - a.priority);`, `const visualOrder = visible.map(d => d.id);\nconst domOrder = modules.map(d => d.id);\nreportOrderConflict(visualOrder, domOrder);`],
    accessibility: [`const fontPx = baseFont * zoom / 100;\nconst requiredHeight = lines * fontPx * lineHeight + padding * 2;`, `cards.attr("height", d => Math.max(d.minHeight, requiredHeight(d)))\n  .attr("aria-label", d => d.label);\ntargets.attr("r", targetSize / 2);`],
    breakpoint: [`const fails = chartWidth < minChart || navWidth > availableWidth;\nconst mode = fails ? "stack" : "columns";`, `if (mode !== previousMode) {\n  cards.transition().duration(400).attr("transform", reflow);\n  breakpointLabel.text(\`switch @ \${width}px\`);\n}`],
    beforeafter: [`const interpolate = d3.interpolateObject(badLayout[id], goodLayout[id]);\nconst current = interpolate(progress);`, `cards.data(modules, d => d.id).join("g")\n  .transition().duration(180)\n  .attr("transform", d => position(currentLayout(d)));`],
    lab: [`const drag = d3.drag().on("drag", (event,d) => {\n  d.x = clamp(event.x - d.w/2); d.y = clamp(event.y - d.h/2);\n  updateLayout(d); updateMetrics();\n});`, `const score = d3.sum([\n  alignment * .35, spacing * .25,\n  hierarchy * .25, overflow * .15\n]);`],
    xray: [`const error = card.x - nearestGridLine(card.x);\nannotations.push({ id: card.id, error, fix: -error });`, `annotation.selectAll("line").data(errors, d => d.id).join("line")\n  .attr("class", d => Math.abs(d.error) > 4 ? "error-line" : "guide-line");`],
    multiscreen: [`const screens = [1200, 768, 375];\nconst views = screens.map(width => ({ width, cards: layoutByWidth(width) }));`, `screenG.selectAll("g.card").data(d => d.cards, d => d.id).join("g")\n  .attr("transform", d => \`translate(\${d.x},\${d.y})\`);`]
  };

  function renderApp() {
    document.documentElement.lang = lang === 'zh' ? 'zh-CN' : 'en';
    document.title = `${chapterIndex + 1}. ${tx(chapter.title)} · ${tx(C.meta.title)}`;
    const topLinks = C.chapters.map((ch, i) => `<a class="${i === chapterIndex ? 'active' : ''}" href="${linkFor(`../${ch.slug}/`)}">${i + 1}. ${tx(ch.title)}</a>`).join('');
    const sectionOptions = chapter.sections.map((s, i) => `<option value="${i}" ${i === activeSection ? 'selected' : ''}>${chapterIndex + 1}.${i + 1} ${tx(s.title)}</option>`).join('');
    const sectionNav = chapter.sections.map((s, i) => `<button data-section="${i}" class="${i === activeSection ? 'active' : ''}"><b>${chapterIndex + 1}.${i + 1}</b><span>${tx(s.title)}</span></button>`).join('');
    const sections = chapter.sections.map((s, i) => renderSection(s, i)).join('');
    const prev = chapterIndex > 0 ? C.chapters[chapterIndex - 1] : null;
    const next = chapterIndex < C.chapters.length - 1 ? C.chapters[chapterIndex + 1] : null;
    document.getElementById('lessonApp').style.setProperty('--accent', chapter.accent);
    document.getElementById('lessonApp').innerHTML = `<nav class="course-topbar" aria-label="${tx(C.ui.chapters)}">
      <a class="back-portal" href="${linkFor('../')}">← ${tx(C.ui.portal)}</a><div class="course-chapter-tabs">${topLinks}</div>
      <div class="lang-switch light"><button data-lang="zh" class="${lang === 'zh' ? 'active' : ''}">中</button><button data-lang="en" class="${lang === 'en' ? 'active' : ''}">EN</button></div>
    </nav>
    <header class="lesson-hero"><div class="lesson-hero-inner"><div><p class="eyebrow">CAMPUS PULSE · PHASE ${String(chapterIndex + 1).padStart(2,'0')}</p><h1>${tx(chapter.title)}</h1><p class="chapter-en">${chapter.title.en}</p><p class="chapter-desc">${tx(chapter.desc)}</p></div><div class="chapter-counter"><span>${tx(C.ui.chapterLabel)}</span><b>0${chapterIndex + 1}</b></div></div></header>
    <main class="lesson-shell"><aside class="chapter-sidebar"><h2>${tx(C.ui.toc)}</h2><nav class="section-nav">${sectionNav}</nav><div class="sidebar-progress"><div class="progress-label"><span>${tx(C.ui.progress)}</span><b>${activeSection + 1} / ${chapter.sections.length}</b></div><div class="progress-track"><i style="width:${(activeSection + 1) / chapter.sections.length * 100}%"></i></div></div></aside>
      <div class="lesson-content"><div class="mobile-section-select"><label for="sectionSelect">${tx(C.ui.menu)}</label><select id="sectionSelect">${sectionOptions}</select></div>${sections}</div>
    </main>
    <nav class="chapter-pager">${prev ? `<a class="pager-link" href="${linkFor(`../${prev.slug}/`)}"><small>← ${tx(C.ui.previous)}</small><b>${tx(prev.title)}</b></a>` : '<span class="pager-link pager-empty"></span>'}<a class="pager-portal" href="${linkFor('../')}">${tx(C.ui.portal)}</a>${next ? `<a class="pager-link next" href="${linkFor(`../${next.slug}/`)}"><small>${tx(C.ui.nextChapter)} →</small><b>${tx(next.title)}</b></a>` : '<span class="pager-link pager-empty"></span>'}</nav>
    <footer class="site-footer">${tx(C.ui.footer)}</footer>`;
    bindEvents();
    renderDemo(chapter.sections[activeSection]);
  }

  function renderSection(s, i) {
    const active = i === activeSection ? ' active' : '';
    const theory = s.theory.map(d => `<li>${tx(d)}</li>`).join('');
    const snippets = CODE[s.demo] || CODE.hierarchy;
    return `<article class="lesson-section${active}" data-section-panel="${i}">
      <header class="section-banner"><span class="section-number">${chapterIndex + 1}.${i + 1}</span><div><h2>${tx(s.title)}</h2><p class="section-en">${s.title.en}</p><p>${tx(s.subtitle)}</p></div></header>
      <div class="lesson-tabs" role="tablist"><button class="active" data-tab="explain">${tx(C.ui.explain)}</button><button data-tab="code">${tx(C.ui.code)}</button><button data-tab="demo">${tx(C.ui.demo)}</button></div>
      <section class="tab-panel active" data-panel="explain"><div class="explain-lead"><div class="case-block"><h3>${tx(C.ui.caseProblem)}</h3><p>${tx(s.subtitle)}</p></div><div class="theory-block"><h3>${tx(C.ui.theory)}</h3><ul>${theory}</ul></div></div><div class="key-pit-grid"><div class="teaching-note"><b>${tx(C.ui.keyPoint)}</b><p>${tx(s.key)}</p></div><div class="teaching-note pit"><b>${tx(C.ui.pitfall)}</b><p>${tx(s.pit)}</p></div></div></section>
      <section class="tab-panel" data-panel="code"><div class="code-stack"><article class="code-point"><header><h3>${tx(C.ui.keyCode1)}</h3><span>01 / MODEL</span></header><pre><code>${highlight(snippets[0])}</code></pre><p><b>${tx(C.ui.why)}：</b> ${tx(s.key)}</p></article><article class="code-point"><header><h3>${tx(C.ui.keyCode2)}</h3><span>02 / UPDATE</span></header><pre><code>${highlight(snippets[1])}</code></pre><p><b>${tx(C.ui.pitfall)}：</b> ${tx(s.pit)}</p></article></div></section>
      <section class="tab-panel" data-panel="demo"><div class="demo-intro"><div><h3>${tx(C.ui.try)}</h3><p>${tx(s.subtitle)}</p></div><span class="demo-tag">D3.JS · INTERACTIVE</span></div><div class="demo-mount" id="demo-${s.id}"></div></section>
    </article>`;
  }

  function highlight(code) {
    return esc(code)
      .replace(/(\/\/[^\n]*)/g, '<span class="cmt">$1</span>')
      .replace(/\b(const|let|if|else|return|new)\b/g, '<span class="fn">$1</span>')
      .replace(/("[^"\n]*"|'[^'\n]*')/g, '<span class="str">$1</span>')
      .replace(/\b(\d+(?:\.\d+)?)\b/g, '<span class="num">$1</span>');
  }

  function bindEvents() {
    document.querySelectorAll('[data-lang]').forEach(btn => btn.addEventListener('click', () => {
      lang = btn.dataset.lang; localStorage.setItem('layout-course-lang', lang);
      const url = new URL(location.href); url.searchParams.set('lang', lang); history.replaceState({}, '', url); renderApp();
    }));
    document.querySelectorAll('.section-nav button').forEach(btn => btn.addEventListener('click', () => switchSection(+btn.dataset.section)));
    const select = document.getElementById('sectionSelect'); if (select) select.addEventListener('change', () => switchSection(+select.value));
    document.querySelectorAll('.lesson-tabs button').forEach(btn => btn.addEventListener('click', () => {
      const section = btn.closest('.lesson-section');
      section.querySelectorAll('.lesson-tabs button').forEach(b => b.classList.toggle('active', b === btn));
      section.querySelectorAll('.tab-panel').forEach(p => p.classList.toggle('active', p.dataset.panel === btn.dataset.tab));
      if (btn.dataset.tab === 'demo') renderDemo(chapter.sections[+section.dataset.sectionPanel]);
    }));
  }

  function switchSection(i) {
    activeSection = i; renderApp();
    document.querySelector('.lesson-shell').scrollIntoView({behavior:'smooth',block:'start'});
  }

  function demoBase(section, controls, extra = '') {
    const mount = document.getElementById(`demo-${section.id}`); if (!mount) return null;
    mount.innerHTML = `<div class="demo-shell"><aside class="demo-controls"><h4>${lang === 'zh' ? '实验参数' : 'LAB CONTROLS'}</h4>${controls}${extra}</aside><div class="demo-canvas"><svg viewBox="0 0 720 430" role="img" aria-label="${esc(tx(section.title))}"></svg><div class="demo-status"></div></div></div>`;
    return { mount, svg:d3.select(mount).select('svg'), status:mount.querySelector('.demo-status'), controls:mount.querySelector('.demo-controls') };
  }
  const range = (id,label,min,max,value,step=1) => `<div class="control-group"><label for="${id}"><span>${label}</span><b id="${id}Out">${value}</b></label><input id="${id}" type="range" min="${min}" max="${max}" value="${value}" step="${step}"></div>`;
  const action = (id,label,primary=false) => `<button id="${id}" class="demo-btn ${primary?'primary':''}">${label}</button>`;
  const statusText = (zh,en) => lang === 'zh' ? zh : en;
  const setStatus = (base, zh, en) => base.status.textContent = statusText(zh,en);
  function defs(svg) { const d=svg.append('defs'); d.append('marker').attr('id','arrow').attr('viewBox','0 0 10 10').attr('refX',8).attr('refY',5).attr('markerWidth',6).attr('markerHeight',6).attr('orient','auto').append('path').attr('d','M0,0 L10,5 L0,10z').attr('fill','#ff6b4a'); }
  const baseModules = () => [
    {id:'chart',value:'8.4K',importance:5},{id:'active',value:'8,392',importance:4},{id:'complete',value:'72%',importance:4},{id:'ranking',value:'#1',importance:3},{id:'recent',value:'24',importance:2},{id:'device',value:'62%',importance:1}
  ];
  function drawCard(g,d) { g.append('rect').attr('class',d.main?'svg-card main':'svg-card').attr('rx',7).attr('width',d.w).attr('height',d.h); g.append('text').attr('class','svg-label').attr('x',12).attr('y',24).text(nameOf(d.id)); g.append('text').attr('class','svg-value').attr('x',12).attr('y',50).text(d.value||''); }

  function renderDemo(section) {
    if (!window.d3) return;
    const fn = {
      audit:demoAudit,matrix:demoMatrix,hierarchy:demoHierarchy,path:demoPath,grid:demoGrid,alignment:demoAlignment,ratio:demoRatio,rhythm:demoRhythm,
      proximity:demoProximity,region:demoRegion,density:demoDensity,composition:demoComposition,responsive:demoResponsive,priority:demoPriority,
      accessibility:demoAccessibility,breakpoint:demoBreakpoint,beforeafter:demoBeforeAfter,lab:demoLab,xray:demoXray,multiscreen:demoMultiscreen
    }[section.demo];
    if (fn) fn(section);
  }

  function demoAudit(section) {
    const issueNames={hierarchy:{zh:'层级',en:'Hierarchy'},alignment:{zh:'对齐',en:'Alignment'},grouping:{zh:'分组',en:'Grouping'},overflow:{zh:'溢出',en:'Overflow'}};
    const controls=Object.entries(issueNames).map(([id,n])=>`<label class="toggle-row"><input type="checkbox" data-issue="${id}"> ${tx(n)}</label>`).join('')+`<div class="demo-actions">${action('auditAll',lang==='zh'?'显示全部问题':'Show all issues',true)}${action('auditReset',tx(C.ui.reset))}</div><div class="metric-list"><div class="metric-row"><span>${lang==='zh'?'诊断覆盖':'Audit coverage'}</span><b id="auditScore">0%</b><i><b id="auditBar" style="width:0%"></b></i></div></div>`;
    const b=demoBase(section,controls); const svg=b.svg; defs(svg);
    const cards=[{id:'active',x:46,y:62,w:170,h:112,value:'8,392'},{id:'chart',x:244,y:52,w:380,h:116,value:'8.4K'},{id:'complete',x:72,y:205,w:238,h:74,value:'72%'},{id:'ranking',x:345,y:205,w:280,h:150,value:'#1'},{id:'recent',x:42,y:326,w:260,h:56,value:'24'}];
    svg.append('rect').attr('class','svg-frame').attr('x',16).attr('y',16).attr('width',688).attr('height',398).attr('rx',10);
    const cg=svg.selectAll('g.card').data(cards).join('g').attr('transform',d=>`translate(${d.x},${d.y})`); cg.each(function(d){drawCard(d3.select(this),d)});
    const issueData={hierarchy:{x:35,y:42,w:600,h:145,label:'01'},alignment:{x:32,y:185,w:610,h:185,label:'02'},grouping:{x:320,y:190,w:320,h:180,label:'03'},overflow:{x:34,y:318,w:285,h:80,label:'04'}};
    const selected=new Set();
    const update=()=>{const data=[...selected].map(k=>({...issueData[k],id:k}));const g=svg.selectAll('g.issue').data(data,d=>d.id).join(enter=>{const n=enter.append('g').attr('class','issue');n.append('rect').attr('fill','none').attr('stroke','#ff6b4a').attr('stroke-width',2).attr('stroke-dasharray','6 4').attr('rx',8);n.append('circle').attr('r',13).attr('fill','#ff6b4a');n.append('text').attr('fill','#fff').attr('font-size',10).attr('font-weight',800).attr('text-anchor','middle').attr('dy','.35em');return n;});g.select('rect').attr('x',d=>d.x).attr('y',d=>d.y).attr('width',d=>d.w).attr('height',d=>d.h);g.select('circle').attr('cx',d=>d.x+10).attr('cy',d=>d.y);g.select('text').attr('x',d=>d.x+10).attr('y',d=>d.y).text(d=>d.label);const score=selected.size/4*100;b.controls.querySelector('#auditScore').textContent=`${score}%`;b.controls.querySelector('#auditBar').style.width=`${score}%`;setStatus(b,score===100?'已定位四类结构问题。下一步先修层级，再修网格。':`已标注 ${selected.size}/4 类问题。`,score===100?'All four structural issue types found. Repair hierarchy first, then the grid.':`${selected.size}/4 issue types marked.`)};
    b.controls.querySelectorAll('[data-issue]').forEach(el=>el.addEventListener('change',()=>{el.checked?selected.add(el.dataset.issue):selected.delete(el.dataset.issue);update()}));b.controls.querySelector('#auditAll').onclick=()=>{b.controls.querySelectorAll('[data-issue]').forEach(el=>{el.checked=true;selected.add(el.dataset.issue)});update()};b.controls.querySelector('#auditReset').onclick=()=>{selected.clear();b.controls.querySelectorAll('[data-issue]').forEach(el=>el.checked=false);update()};update();
  }

  function demoMatrix(section) {
    const b=demoBase(section,`<p style="font-size:.8rem;color:var(--muted)">${lang==='zh'?'拖动模块：横轴是使用频率，纵轴是决策影响。':'Drag modules: frequency is horizontal; decision impact is vertical.'}</p><div class="metric-list" id="priorityList"></div>`);const svg=b.svg, x=d3.scaleLinear().domain([1,5]).range([75,675]),y=d3.scaleLinear().domain([1,5]).range([365,45]);
    const data=baseModules().slice(0,5).map((d,i)=>({...d,frequency:[4.6,4.2,3.3,2.1,1.5][i],impact:[4.8,3.4,4.0,2.6,1.5][i]}));
    svg.append('g').attr('class','axis').attr('transform','translate(0,365)').call(d3.axisBottom(x).ticks(5));svg.append('g').attr('class','axis').attr('transform','translate(75,0)').call(d3.axisLeft(y).ticks(5));svg.append('line').attr('x1',x(3)).attr('x2',x(3)).attr('y1',45).attr('y2',365).attr('class','guide-line');svg.append('line').attr('x1',75).attr('x2',675).attr('y1',y(3)).attr('y2',y(3)).attr('class','guide-line');svg.append('text').attr('class','svg-meta').attr('x',675).attr('y',405).attr('text-anchor','end').text(lang==='zh'?'任务频率 →':'TASK FREQUENCY →');svg.append('text').attr('class','svg-meta').attr('transform','translate(22,45) rotate(-90)').text(lang==='zh'?'决策影响 →':'DECISION IMPACT →');
    const update=()=>{const node=svg.selectAll('g.node').data(data,d=>d.id).join(enter=>{const g=enter.append('g').attr('class','node drag-card');g.append('circle').attr('r',28).attr('fill',chapter.accent).attr('fill-opacity','.88');g.append('text').attr('text-anchor','middle').attr('dy','.32em').attr('fill','#fff').attr('font-size',9).attr('font-weight',750);return g;}).attr('transform',d=>`translate(${x(d.frequency)},${y(d.impact)})`);node.select('text').text(d=>nameOf(d.id));node.call(d3.drag().on('drag',(e,d)=>{d.frequency=Math.max(1,Math.min(5,x.invert(e.x)));d.impact=Math.max(1,Math.min(5,y.invert(e.y)));update()}));const ranked=[...data].sort((a,b)=>b.frequency*b.impact-a.frequency*a.impact);b.controls.querySelector('#priorityList').innerHTML=ranked.slice(0,4).map((d,i)=>`<div class="metric-row"><span>0${i+1} ${nameOf(d.id)}</span><b>${(d.frequency*d.impact).toFixed(1)}</b><i><b style="width:${d.frequency*d.impact/25*100}%"></b></i></div>`).join('');setStatus(b,`当前核心层：${nameOf(ranked[0].id)}。优先级来自频率 × 影响。`,`Current core layer: ${nameOf(ranked[0].id)}. Priority comes from frequency × impact.`)};update();
  }

  function hierarchyLayout(data){const sorted=[...data].sort((a,b)=>b.importance-a.importance),scale=d3.scaleLinear().domain([1,5]).range([120,370]);let x=38,y=55,rowH=0;return sorted.map(d=>{const w=Math.min(scale(d.importance),640);const h=d.importance>=5?160:d.importance>=3?94:68;if(x+w>680){x=38;y+=rowH+15;rowH=0}const out={...d,x,y,w,h};x+=w+15;rowH=Math.max(rowH,h);return out})}
  function hierarchyControls(data,showPath){return data.slice(0,5).map(d=>range(`imp-${d.id}`,nameOf(d.id),1,5,d.importance)).join('')+`<label class="toggle-row"><input id="showRead" type="checkbox" ${showPath?'checked':''}> ${lang==='zh'?'显示启发式阅读路径':'Show heuristic reading path'}</label>`}
  function demoHierarchy(section,forcePath=false) {const data=baseModules().slice(0,5);const b=demoBase(section,hierarchyControls(data,forcePath));const svg=b.svg;defs(svg);svg.append('rect').attr('class','svg-frame').attr('x',15).attr('y',15).attr('width',690).attr('height',400).attr('rx',10);const update=()=>{const layout=hierarchyLayout(data);const cards=svg.selectAll('g.hcard').data(layout,d=>d.id).join(enter=>{const g=enter.append('g').attr('class','hcard');g.each(function(d){drawCard(d3.select(this),d)});return g;});cards.transition().duration(450).attr('transform',d=>`translate(${d.x},${d.y})`);cards.select('rect').transition().duration(450).attr('width',d=>d.w).attr('height',d=>d.h).attr('class',d=>d.importance===5?'svg-card main':'svg-card');const show=b.controls.querySelector('#showRead').checked;const pts=layout.map(d=>[d.x+d.w/2,d.y+d.h/2]);svg.selectAll('path.reading-path').data(show?[pts]:[]).join('path').attr('class','reading-path').attr('d',d3.line().curve(d3.curveCatmullRom.alpha(.35)));setStatus(b,show?'路径按视觉重量排序；它解释设计意图，不是眼动数据。':'提高模块重要性，观察它获得的面积与位置。',show?'The path follows visual weight; it explains intent, not eye-tracking data.':'Raise a module’s importance and watch it gain area and position.')};data.forEach(d=>{const el=b.controls.querySelector(`#imp-${d.id}`);el.addEventListener('input',()=>{d.importance=+el.value;b.controls.querySelector(`#imp-${d.id}Out`).textContent=el.value;update()})});b.controls.querySelector('#showRead').addEventListener('change',update);update()}
  function demoPath(section){demoHierarchy(section,true)}

  function demoGridCore(section,brokenStart=false){let state={columns:12,margin:46,gutter:14,broken:brokenStart};const controls=range('gridCols',lang==='zh'?'列数':'Columns',6,12,12)+range('gridMargin',lang==='zh'?'边距':'Margin',24,72,46)+range('gridGutter',lang==='zh'?'沟槽':'Gutter',6,28,14)+`<label class="toggle-row"><input id="showGrid" type="checkbox" checked> ${lang==='zh'?'显示网格':'Show grid'}</label><div class="demo-actions">${action('breakGrid',lang==='zh'?'打乱网格':'Break grid')}${action('snapGrid',lang==='zh'?'吸附网格':'Snap to grid',true)}</div><div class="metric-list"><div class="metric-row"><span>${lang==='zh'?'平均对齐误差':'Mean alignment error'}</span><b id="alignError">0 px</b><i><b id="alignBar" style="width:100%"></b></i></div></div>`;const b=demoBase(section,controls),svg=b.svg;const data=[{id:'active',col:0,span:3,y:60,h:80,value:'8,392'},{id:'complete',col:3,span:3,y:60,h:80,value:'72%'},{id:'ranking',col:6,span:3,y:60,h:80,value:'#1'},{id:'device',col:9,span:3,y:60,h:80,value:'62%'},{id:'chart',col:0,span:8,y:158,h:200,value:'8.4K'},{id:'recent',col:8,span:4,y:158,h:200,value:'24'}];const offsets=new Map(data.map((d,i)=>[d.id,brokenStart?{x:(i%2?13:-9),y:(i%3-1)*8}:{x:0,y:0}]));
    const update=()=>{svg.selectAll('*').remove();svg.append('rect').attr('class','svg-frame').attr('x',12).attr('y',12).attr('width',696).attr('height',406).attr('rx',10);const inner=720-state.margin*2,step=inner/state.columns,band=step-state.gutter;if(b.controls.querySelector('#showGrid').checked)svg.selectAll('rect.grid-guide').data(d3.range(state.columns)).join('rect').attr('class','grid-guide').attr('x',d=>state.margin+d*step).attr('y',43).attr('width',Math.max(2,band)).attr('height',342);const layout=data.map(d=>{const off=offsets.get(d.id);return {...d,x:state.margin+d.col*step+off.x,y:d.y+off.y,w:d.span*step-state.gutter}});const cards=svg.selectAll('g.gcard').data(layout,d=>d.id).join('g').attr('class','gcard').attr('transform',d=>`translate(${d.x},${d.y})`);cards.each(function(d){drawCard(d3.select(this),d)});const errors=layout.map(d=>Math.abs(offsets.get(d.id).x));const error=d3.mean(errors);b.controls.querySelector('#alignError').textContent=`${error.toFixed(1)} px`;b.controls.querySelector('#alignBar').style.width=`${Math.max(0,100-error*6)}%`;setStatus(b,state.broken?'轻微偏移累积成明显视觉噪声。点击“吸附网格”。':`${state.columns} 列共享同一套边缘与沟槽。`,state.broken?'Small offsets accumulate into visible noise. Snap the cards back to the grid.':`${state.columns} columns now share the same edges and gutters.`)};
    [['gridCols','columns'],['gridMargin','margin'],['gridGutter','gutter']].forEach(([id,key])=>{const el=b.controls.querySelector(`#${id}`);el.oninput=()=>{state[key]=+el.value;b.controls.querySelector(`#${id}Out`).textContent=el.value;offsets.forEach(v=>{v.x=0;v.y=0});state.broken=false;update()}});b.controls.querySelector('#showGrid').onchange=update;b.controls.querySelector('#breakGrid').onclick=()=>{offsets.forEach((v,k)=>{const i=data.findIndex(d=>d.id===k);v.x=(i%2?1:-1)*(8+i*2);v.y=(i%3-1)*7});state.broken=true;update()};b.controls.querySelector('#snapGrid').onclick=()=>{offsets.forEach(v=>{v.x=0;v.y=0});state.broken=false;update()};update()}
  function demoGrid(section){demoGridCore(section,false)}function demoAlignment(section){demoGridCore(section,true)}

  function demoRatio(section){let pct=68;const b=demoBase(section,range('mainPct',lang==='zh'?'主栏比例':'Main column',48,80,pct)+`<div class="metric-list"><div class="metric-row"><span>${lang==='zh'?'文本可读性':'Text readability'}</span><b id="readability">—</b><i><b id="ratioBar"></b></i></div></div>`);const svg=b.svg;const update=()=>{svg.selectAll('*').remove();const x=35,y=55,total=650,gap=18,main=(total-gap)*pct/100,side=total-gap-main;svg.append('rect').attr('class','svg-frame').attr('x',18).attr('y',20).attr('width',684).attr('height',385).attr('rx',10);const data=[{id:'chart',x,y,w:main,h:290,value:'8.4K',main:true},{id:'ranking',x:x+main+gap,y,w:side,h:290,value:'#1'}];const g=svg.selectAll('g').data(data).join('g').attr('transform',d=>`translate(${d.x},${d.y})`);g.each(function(d){drawCard(d3.select(this),d)});const chars=Math.round(main/7.3),ok=chars>=45&&chars<=75;b.controls.querySelector('#readability').textContent=`${chars} ${lang==='zh'?'字/行':'chars/line'}`;b.controls.querySelector('#ratioBar').style.width=`${ok?92:52}%`;b.controls.querySelector('#ratioBar').style.background=ok?'var(--success)':'var(--gold)';setStatus(b,ok?'主栏可容纳舒适行长，侧栏仍保留足够上下文。':'当前比例让正文行长或侧栏宽度进入风险区。',ok?'The main column supports a comfortable line length while preserving sidebar context.':'This ratio pushes line length or sidebar width into a risk zone.')};const el=b.controls.querySelector('#mainPct');el.oninput=()=>{pct=+el.value;b.controls.querySelector('#mainPctOut').textContent=`${pct}%`;update()};b.controls.querySelector('#mainPctOut').textContent=`${pct}%`;update()}

  function demoRhythm(section){let base=8,density=3;const b=demoBase(section,range('spaceBase',lang==='zh'?'基础单位':'Base unit',4,12,base)+range('densityRows',lang==='zh'?'内容行数':'Content rows',2,6,density)+`<label class="toggle-row"><input id="baseline" type="checkbox" checked> ${lang==='zh'?'显示基线':'Show baseline'}</label>`);const svg=b.svg;const update=()=>{svg.selectAll('*').remove();svg.append('rect').attr('class','svg-frame').attr('x',30).attr('y',20).attr('width',660).attr('height',390).attr('rx',10);if(b.controls.querySelector('#baseline').checked)svg.selectAll('line.base').data(d3.range(52,390,base)).join('line').attr('class','guide-line').attr('x1',45).attr('x2',675).attr('y1',d=>d).attr('y2',d=>d).attr('opacity','.25');const rows=d3.range(density).map(i=>({id:i,x:55,y:62+i*(42+base*2),w:610,h:42}));const g=svg.selectAll('g.row').data(rows,d=>d.id).join('g').attr('transform',d=>`translate(${d.x},${d.y})`);g.append('rect').attr('class','svg-card').attr('rx',6).attr('width',d=>d.w).attr('height',d=>d.h);g.append('circle').attr('cx',18).attr('cy',21).attr('r',7).attr('fill',chapter.accent);g.append('line').attr('x1',38).attr('x2',250).attr('y1',16).attr('y2',16).attr('stroke','#aeb7c8').attr('stroke-width',5).attr('stroke-linecap','round');g.append('line').attr('x1',38).attr('x2',360).attr('y1',28).attr('y2',28).attr('stroke','#d4dae6').attr('stroke-width',4).attr('stroke-linecap','round');setStatus(b,`基础单位 ${base}px 生成 ${base*2}/${base*3}/${base*5}px 的语义间距。`,`A ${base}px base creates semantic gaps of ${base*2}/${base*3}/${base*5}px.`)};[['spaceBase','base'],['densityRows','density']].forEach(([id,key])=>{const el=b.controls.querySelector('#'+id);el.oninput=()=>{if(key==='base')base=+el.value;else density=+el.value;b.controls.querySelector('#'+id+'Out').textContent=el.value;update()}});b.controls.querySelector('#baseline').onchange=update;update()}

  function demoGroupingCore(section,regionStart=false){let inside=12,between=72,region=regionStart;const b=demoBase(section,range('insideGap',lang==='zh'?'组内距离':'Within-group gap',4,34,inside)+range('betweenGap',lang==='zh'?'组间距离':'Between-group gap',24,120,between)+`<label class="toggle-row"><input id="commonRegion" type="checkbox" ${region?'checked':''}> ${lang==='zh'?'显示共同区域':'Show common region'}</label><div class="metric-list"><div class="metric-row"><span>${lang==='zh'?'分组强度':'Grouping strength'}</span><b id="groupRatio">—</b><i><b id="groupBar"></b></i></div></div>`);const svg=b.svg;const update=()=>{svg.selectAll('*').remove();svg.append('rect').attr('class','svg-frame').attr('x',18).attr('y',18).attr('width',684).attr('height',394).attr('rx',10);const cw=120,ch=98,total=cw*4+inside*2+between,start=(720-total)/2,y=155;const data=['active','complete','ranking','device'].map((id,i)=>({id,group:i<2?0:1,x:start+i*cw+(i%2)*inside+(i>=2?inside+between:0),y,w:cw,h:ch,value:["8,392","72%","#1","62%"][i]}));if(region){const groups=d3.groups(data,d=>d.group).map(([key,a])=>({key,x:d3.min(a,d=>d.x)-15,w:d3.max(a,d=>d.x)+cw-d3.min(a,d=>d.x)+30}));svg.selectAll('rect.region').data(groups).join('rect').attr('x',d=>d.x).attr('y',y-35).attr('width',d=>d.w).attr('height',ch+70).attr('rx',13).attr('fill',chapter.accent).attr('fill-opacity','.07').attr('stroke',chapter.accent).attr('stroke-opacity','.35')};const g=svg.selectAll('g.card').data(data,d=>d.id).join('g').attr('transform',d=>`translate(${d.x},${d.y})`);g.each(function(d){drawCard(d3.select(this),d)});const ratio=between/inside,score=Math.min(100,ratio/4*100);b.controls.querySelector('#groupRatio').textContent=`${ratio.toFixed(1)}×`;b.controls.querySelector('#groupBar').style.width=`${score}%`;setStatus(b,ratio>=2.5?'组内与组间距离差异清晰，关系容易被感知。':'两种距离过于接近，四张卡片看起来属于同一组。',ratio>=2.5?'The gap ratio is clear enough for grouping to be perceived.':'The two gaps are too similar; all four cards appear to belong together.')};[['insideGap','inside'],['betweenGap','between']].forEach(([id,key])=>{const el=b.controls.querySelector('#'+id);el.oninput=()=>{key==='inside'?inside=+el.value:between=+el.value;b.controls.querySelector('#'+id+'Out').textContent=el.value;update()}});b.controls.querySelector('#commonRegion').onchange=e=>{region=e.target.checked;update()};update()}
  function demoProximity(s){demoGroupingCore(s,false)}function demoRegion(s){demoGroupingCore(s,true)}

  function demoDensity(section){let count=7,pad=16;const b=demoBase(section,range('densityCount',lang==='zh'?'模块数量':'Module count',4,12,count)+range('densityPad',lang==='zh'?'卡片内边距':'Card padding',6,30,pad)+`<div class="metric-list"><div class="metric-row"><span>${lang==='zh'?'拥挤风险':'Crowding risk'}</span><b id="crowdRisk">—</b><i><b id="crowdBar"></b></i></div></div>`);const svg=b.svg;const update=()=>{svg.selectAll('*').remove();svg.append('rect').attr('class','svg-frame').attr('x',22).attr('y',18).attr('width',676).attr('height',394).attr('rx',10);const cols=count>8?4:count>5?3:2,gap=Math.max(5,30-pad*.75),cw=(620-gap*(cols-1))/cols;const data=d3.range(count).map(i=>({id:i,x:50+(i%cols)*(cw+gap),y:52+Math.floor(i/cols)*(88+gap),w:cw,h:88}));const g=svg.selectAll('g.dcard').data(data,d=>d.id).join('g').attr('transform',d=>`translate(${d.x},${d.y})`);g.append('rect').attr('class','svg-card').attr('rx',6).attr('width',d=>d.w).attr('height',d=>d.h);g.append('text').attr('class','svg-meta').attr('x',pad).attr('y',pad+10).text((d,i)=>`${lang==='zh'?'模块':'MODULE'} ${i+1}`);g.append('line').attr('x1',pad).attr('x2',d=>Math.max(pad+15,d.w-pad)).attr('y1',pad+30).attr('y2',pad+30).attr('stroke','#c7cfdd').attr('stroke-width',5).attr('stroke-linecap','round');const risk=Math.min(100,Math.max(0,(count-5)*10+(16-pad)*2));b.controls.querySelector('#crowdRisk').textContent=`${Math.round(risk)}%`;b.controls.querySelector('#crowdBar').style.width=`${risk}%`;b.controls.querySelector('#crowdBar').style.background=risk>65?'var(--coral)':risk>35?'var(--gold)':'var(--success)';setStatus(b,risk<40?'密度与留白处于可扫描区间。':'单位注意力中的对象过多；考虑合并或渐进披露。',risk<40?'Density and whitespace remain scannable.':'Too many objects compete for attention; consider grouping or progressive disclosure.')};[['densityCount','count'],['densityPad','pad']].forEach(([id,key])=>{const el=b.controls.querySelector('#'+id);el.oninput=()=>{key==='count'?count=+el.value:pad=+el.value;b.controls.querySelector('#'+id+'Out').textContent=el.value;update()}});update()}

  function demoComposition(section){let mode='dashboard';const b=demoBase(section,`<div class="control-group"><label>${lang==='zh'?'主要任务':'Primary task'}</label><select id="compositionMode"><option value="dashboard">${lang==='zh'?'监控与比较':'Monitor and compare'}</option><option value="article">${lang==='zh'?'连续阅读':'Continuous reading'}</option><option value="form">${lang==='zh'?'逐步填写':'Step-by-step input'}</option></select></div>`);const svg=b.svg;const layouts={dashboard:[['chart',45,100,400,235],['active',45,40,125,48],['complete',185,40,125,48],['ranking',465,100,205,235],['recent',45,350,625,42]],article:[['chart',165,70,390,180],['active',165,270,185,58],['complete',370,270,185,58],['recent',165,345,390,42],['ranking',45,70,95,317]],form:[['active',170,58,380,60],['complete',170,135,380,60],['chart',170,212,380,92],['ranking',170,320,180,55],['recent',370,320,180,55]]};const values={chart:'8.4K',active:'8,392',complete:'72%',ranking:'#1',recent:'24'};const update=()=>{svg.selectAll('*').remove();svg.append('rect').attr('class','svg-frame').attr('x',20).attr('y',18).attr('width',680).attr('height',394).attr('rx',10);const data=layouts[mode].map(([id,x,y,w,h])=>({id,x,y,w,h,value:values[id],main:id==='chart'}));const g=svg.selectAll('g.comp').data(data,d=>d.id).join('g').attr('transform',d=>`translate(${d.x},${d.y})`);g.each(function(d){drawCard(d3.select(this),d)});const labels={dashboard:['监控任务需要并列比较与持续可见。','Monitoring needs side-by-side comparison and persistent visibility.'],article:['阅读任务需要稳定行长和连续流。','Reading needs stable line length and a continuous flow.'],form:['填写任务需要明确顺序与单一焦点。','Input tasks need clear sequence and a single focus.']};setStatus(b,...labels[mode])};b.controls.querySelector('#compositionMode').onchange=e=>{mode=e.target.value;update()};update()}

  function layoutForWidth(w,priority=false){const ids=priority?['chart','active','complete','ranking','recent']:['active','complete','ranking','chart','recent'];const pad=24,gap=14;if(w<520){return ids.map((id,i)=>({id,x:pad,y:48+i*68,w:w-pad*2,h:id==='chart'?108:54,value:{chart:'8.4K',active:'8,392',complete:'72%',ranking:'#1',recent:'24'}[id]}))}if(w<850){const cw=(w-pad*2-gap)/2;return ids.map((id,i)=>({id,x:pad+(i%2)*(cw+gap),y:52+Math.floor(i/2)*90,w:cw,h:id==='chart'?150:74,value:{chart:'8.4K',active:'8,392',complete:'72%',ranking:'#1',recent:'24'}[id]}))}const cw=(w-pad*2-gap*3)/4;return [{id:'active',x:pad,y:52,w:cw,h:66,value:'8,392'},{id:'complete',x:pad+cw+gap,y:52,w:cw,h:66,value:'72%'},{id:'ranking',x:pad+2*(cw+gap),y:52,w:cw,h:66,value:'#1'},{id:'recent',x:pad+3*(cw+gap),y:52,w:cw,h:66,value:'24'},{id:'chart',x:pad,y:136,w:cw*3+gap*2,h:190,value:'8.4K',main:true},{id:'device',x:pad+3*(cw+gap),y:136,w:cw,h:190,value:'62%'}]}
  function demoResponsiveCore(section,priority=false){let width=priority?430:980;const b=demoBase(section,range('viewportWidth',lang==='zh'?'视口宽度':'Viewport width',320,1200,width)+`<div class="metric-list"><div class="metric-row"><span>${lang==='zh'?'布局模式':'Layout mode'}</span><b id="modeOut">—</b><i><b style="width:100%"></b></i></div></div>`);const svg=b.svg;const update=()=>{svg.selectAll('*').remove();const mode=width<520?'MOBILE · 1 COL':width<850?'TABLET · 2 COL':'DESKTOP · 4 COL',frameW=640,frameX=40;svg.append('rect').attr('x',frameX).attr('y',20).attr('width',frameW).attr('height',392).attr('rx',12).attr('fill','#e8ebf3').attr('stroke','#cfd6e5');const innerScale=d3.scaleLinear().domain([0,width]).range([frameX+8,frameX+frameW-8]);const scale=(frameW-16)/width;const viewport=svg.append('g').attr('transform',`translate(${frameX+8},30) scale(${scale})`);viewport.append('rect').attr('width',width).attr('height',370/scale).attr('fill','#fff').attr('rx',8/scale);const data=layoutForWidth(width,priority);const g=viewport.selectAll('g.rcard').data(data,d=>d.id).join('g').attr('transform',d=>`translate(${d.x},${d.y})`);g.append('rect').attr('class',d=>d.id==='chart'?'svg-card main':'svg-card').attr('rx',6/scale).attr('width',d=>d.w).attr('height',d=>d.h).attr('stroke-width',1.4/scale);g.append('text').attr('class','svg-label').attr('x',10).attr('y',20).attr('font-size',Math.max(10,12/scale)).text(d=>nameOf(d.id));b.controls.querySelector('#modeOut').textContent=mode;setStatus(b,priority?'窄屏按任务优先级重排，主图先于辅助模块。':'卡片不是整体缩小，而是在阈值处改变列数与顺序。',priority?'Narrow screens reorder by task priority, placing the main chart before support modules.':'Cards do not scale down as a whole; columns and order change at thresholds.')};const el=b.controls.querySelector('#viewportWidth');el.oninput=()=>{width=+el.value;b.controls.querySelector('#viewportWidthOut').textContent=`${width}px`;update()};b.controls.querySelector('#viewportWidthOut').textContent=`${width}px`;update()}
  function demoResponsive(s){demoResponsiveCore(s,false)}function demoPriority(s){demoResponsiveCore(s,true)}

  function demoAccessibility(section){let zoom=150,target=44;const b=demoBase(section,range('textZoom',lang==='zh'?'文字缩放':'Text zoom',100,200,zoom,10)+range('targetSize',lang==='zh'?'触控目标':'Touch target',28,60,target)+`<div class="metric-list"><div class="metric-row"><span>${lang==='zh'?'布局稳健性':'Layout robustness'}</span><b id="a11yScore">—</b><i><b id="a11yBar"></b></i></div></div>`);const svg=b.svg;const update=()=>{svg.selectAll('*').remove();svg.append('rect').attr('class','svg-frame').attr('x',55).attr('y',24).attr('width',610).attr('height',380).attr('rx',10);const fs=14*zoom/100,line=fs*1.5,cardH=Math.max(92,line*2+42);const data=[{id:'active',x:85,y:65,w:250,h:cardH,value:'8,392'},{id:'complete',x:365,y:65,w:250,h:cardH,value:'72%'},{id:'chart',x:85,y:80+cardH,w:530,h:Math.max(150,line*3+60),value:'8.4K'}];const g=svg.selectAll('g.acard').data(data).join('g').attr('transform',d=>`translate(${d.x},${d.y})`);g.append('rect').attr('class','svg-card').attr('rx',7).attr('width',d=>d.w).attr('height',d=>d.h);g.append('text').attr('x',16).attr('y',28).attr('fill','#3b4358').attr('font-size',fs).attr('font-weight',750).text(d=>nameOf(d.id));g.append('text').attr('x',16).attr('y',28+line).attr('fill','#11182b').attr('font-size',fs*1.35).attr('font-weight',850).text(d=>d.value);g.append('circle').attr('cx',d=>d.w-target/2-8).attr('cy',target/2+8).attr('r',target/2).attr('fill',chapter.accent).attr('fill-opacity','.14').attr('stroke',chapter.accent);const score=Math.max(0,100-Math.max(0,44-target)*4);b.controls.querySelector('#a11yScore').textContent=`${score}%`;b.controls.querySelector('#a11yBar').style.width=`${score}%`;b.controls.querySelector('#a11yBar').style.background=score>85?'var(--success)':'var(--coral)';setStatus(b,target>=44?'组件高度随文字增长，触控目标保持至少 44px。':'触控目标低于 44px，手指操作风险上升。',target>=44?'Components grow with text, and targets remain at least 44px.':'Targets are below 44px, increasing touch error risk.')};[['textZoom','zoom'],['targetSize','target']].forEach(([id,key])=>{const el=b.controls.querySelector('#'+id);el.oninput=()=>{key==='zoom'?zoom=+el.value:target=+el.value;b.controls.querySelector('#'+id+'Out').textContent=key==='zoom'?`${el.value}%`:`${el.value}px`;update()}});b.controls.querySelector('#textZoomOut').textContent=`${zoom}%`;b.controls.querySelector('#targetSizeOut').textContent=`${target}px`;update()}

  function demoBreakpoint(section){let width=760,minChart=430;const b=demoBase(section,range('bpWidth',lang==='zh'?'容器宽度':'Container width',420,1100,width)+range('minChart',lang==='zh'?'图表最低宽度':'Minimum chart width',320,560,minChart)+`<div class="metric-list"><div class="metric-row"><span>${lang==='zh'?'当前判断':'Current decision'}</span><b id="bpDecision">—</b><i><b id="bpBar" style="width:100%"></b></i></div></div>`);const svg=b.svg;const update=()=>{svg.selectAll('*').remove();const fails=width*.68<minChart,mode=fails?'STACK':'COLUMNS',frameW=620,scale=frameW/width;svg.append('rect').attr('x',50).attr('y',24).attr('width',620).attr('height',370).attr('rx',10).attr('fill','#fff').attr('stroke','#cfd6e5');const g=svg.append('g').attr('transform',`translate(50,35) scale(${scale})`);const mainW=fails?width-48:(width-66)*.68,sideW=fails?width-48:(width-66)*.32;const data=fails?[{id:'chart',x:24,y:40,w:mainW,h:145},{id:'ranking',x:24,y:202,w:sideW,h:95}]:[{id:'chart',x:24,y:40,w:mainW,h:255},{id:'ranking',x:42+mainW,y:40,w:sideW,h:255}];const cards=g.selectAll('g').data(data).join('g').attr('transform',d=>`translate(${d.x},${d.y})`);cards.append('rect').attr('class','svg-card').attr('width',d=>d.w).attr('height',d=>d.h).attr('rx',7/scale);cards.append('text').attr('class','svg-label').attr('x',14).attr('y',25).attr('font-size',12/scale).text(d=>nameOf(d.id));b.controls.querySelector('#bpDecision').textContent=mode;setStatus(b,fails?`主图预计只有 ${Math.round(width*.68)}px，小于最低 ${minChart}px，因此切换为上下堆叠。`:`主图仍有 ${Math.round(width*.68)}px，可以保留双栏。`,fails?`The chart would have ${Math.round(width*.68)}px, below its ${minChart}px minimum, so the layout stacks.`:`The chart retains ${Math.round(width*.68)}px, so columns remain viable.`)};[['bpWidth','width'],['minChart','minChart']].forEach(([id,key])=>{const el=b.controls.querySelector('#'+id);el.oninput=()=>{key==='width'?width=+el.value:minChart=+el.value;b.controls.querySelector('#'+id+'Out').textContent=`${el.value}px`;update()}});b.controls.querySelector('#bpWidthOut').textContent=`${width}px`;b.controls.querySelector('#minChartOut').textContent=`${minChart}px`;update()}

  const badGood={
    chart:{bad:[245,55,360,105],good:[45,145,430,190]},active:{bad:[48,48,170,112],good:[45,55,135,70]},complete:{bad:[70,218,220,72],good:[195,55,135,70]},ranking:{bad:[335,200,285,140],good:[493,145,180,190]},recent:{bad:[42,350,275,45],good:[45,352,628,45]}
  };
  function demoBeforeAfter(section){let stage=0;const labels=lang==='zh'?['混乱初稿','层级','网格','分组','响应式完成']:['Chaotic draft','Hierarchy','Grid','Grouping','Responsive finish'];const b=demoBase(section,range('caseStage',lang==='zh'?'重构阶段':'Redesign stage',0,4,stage)+`<div class="metric-list"><div class="metric-row"><span>${lang==='zh'?'当前阶段':'Current stage'}</span><b id="stageName">—</b><i><b id="stageBar"></b></i></div></div>`);const svg=b.svg;const data=baseModules().filter(d=>badGood[d.id]);const update=()=>{svg.selectAll('*').remove();svg.append('rect').attr('class','svg-frame').attr('x',18).attr('y',18).attr('width',684).attr('height',394).attr('rx',10);const t=stage/4,layout=data.map(d=>{const p=d3.interpolateArray(badGood[d.id].bad,badGood[d.id].good)(t);return {...d,x:p[0],y:p[1],w:p[2],h:p[3],main:d.id==='chart'}});const g=svg.selectAll('g').data(layout,d=>d.id).join('g').attr('transform',d=>`translate(${d.x},${d.y})`);g.each(function(d){drawCard(d3.select(this),d)});b.controls.querySelector('#stageName').textContent=labels[stage];b.controls.querySelector('#stageBar').style.width=`${stage/4*100}%`;setStatus(b,stage===0?'同一组模块没有层级、共享边缘或清晰分组。':`阶段 ${stage}：${labels[stage]}。所有模块身份保持不变。`,stage===0?'The same modules lack hierarchy, shared edges, and grouping.':`Stage ${stage}: ${labels[stage]}. Every module keeps its identity.`)};const el=b.controls.querySelector('#caseStage');el.oninput=()=>{stage=+el.value;b.controls.querySelector('#caseStageOut').textContent=`${stage}/4`;update()};b.controls.querySelector('#caseStageOut').textContent='0/4';update()}

  function labMetrics(cards){const nearest=(v,step,offset=30)=>Math.round((v-offset)/step)*step+offset;const errors=cards.flatMap(d=>[Math.abs(d.x-nearest(d.x,80)),Math.abs(d.y-nearest(d.y,50,50))]);const alignment=Math.max(0,100-d3.mean(errors)*3);const gaps=cards.slice().sort((a,b)=>a.y-b.y).slice(1).map((d,i)=>Math.abs((d.y-(cards[i]?.y||0))-100));const spacing=Math.max(0,100-(d3.mean(gaps)||0));const main=cards.find(d=>d.id==='chart'),maxOther=d3.max(cards.filter(d=>d.id!=='chart'),d=>d.w*d.h);const hierarchy=Math.min(100,(main.w*main.h/maxOther)*42);const overflow=cards.filter(d=>d.x>=24&&d.y>=34&&d.x+d.w<=696&&d.y+d.h<=410).length/cards.length*100;return{alignment,spacing,hierarchy,overflow}}
  function demoLabCore(section,xrayStart=false){let xray=xrayStart;const cards=[{id:'chart',x:42,y:145,w:390,h:180,value:'8.4K'},{id:'active',x:43,y:53,w:150,h:70,value:'8,392'},{id:'complete',x:221,y:62,w:145,h:70,value:'72%'},{id:'ranking',x:470,y:142,w:185,h:180,value:'#1'},{id:'recent',x:48,y:344,w:410,h:48,value:'24'}];const b=demoBase(section,`<label class="toggle-row"><input id="labXray" type="checkbox" ${xray?'checked':''}> ${lang==='zh'?'打开 Layout X-Ray':'Turn on Layout X-Ray'}</label><div class="demo-actions">${action('messLab',lang==='zh'?'制造问题':'Make it messy')}${action('resetLab',tx(C.ui.reset),true)}</div><div class="metric-list" id="labMetrics"></div><p style="margin-top:16px;font-size:.72rem;color:var(--muted)">${tx(C.ui.heuristic)}</p>`);const svg=b.svg;const initial=cards.map(d=>({...d}));
    const update=()=>{svg.selectAll('*').remove();svg.append('rect').attr('class','svg-frame').attr('x',16).attr('y',16).attr('width',688).attr('height',398).attr('rx',10);if(xray){svg.selectAll('line.v').data(d3.range(30,700,80)).join('line').attr('class','guide-line').attr('x1',d=>d).attr('x2',d=>d).attr('y1',30).attr('y2',410);svg.selectAll('line.h').data(d3.range(50,410,50)).join('line').attr('class','guide-line').attr('x1',24).attr('x2',696).attr('y1',d=>d).attr('y2',d=>d)}const drag=d3.drag().on('drag',(e,d)=>{d.x=Math.max(20,Math.min(700-d.w,e.x-d.w/2));d.y=Math.max(20,Math.min(414-d.h,e.y-d.h/2));update()}).on('end',(e,d)=>{d.x=Math.max(30,Math.min(670-d.w,Math.round((d.x-30)/80)*80+30));d.y=Math.max(50,Math.min(410-d.h,Math.round((d.y-50)/50)*50+50));update()});const g=svg.selectAll('g.drag-card').data(cards,d=>d.id).join('g').attr('class','drag-card').attr('transform',d=>`translate(${d.x},${d.y})`).call(drag);g.each(function(d){drawCard(d3.select(this),d)});if(xray)g.append('text').attr('class','svg-meta').attr('x',d=>d.w-8).attr('y',d=>d.h-8).attr('text-anchor','end').text(d=>`${d.x},${d.y} · ${d.w}×${d.h}`);const m=labMetrics(cards),score=Math.round(m.alignment*.35+m.spacing*.25+m.hierarchy*.25+m.overflow*.15);b.controls.querySelector('#labMetrics').innerHTML=Object.entries(m).map(([k,v])=>`<div class="metric-row"><span>${({alignment:lang==='zh'?'对齐':'Alignment',spacing:lang==='zh'?'节奏':'Rhythm',hierarchy:lang==='zh'?'层级':'Hierarchy',overflow:lang==='zh'?'边界':'Bounds'})[k]}</span><b>${Math.round(v)}%</b><i><b style="width:${v}%"></b></i></div>`).join('');setStatus(b,`教学启发式 ${score}/100。${m.alignment<70?'下一步：先把边缘吸附到网格。':'下一步：检查主图是否足够突出。'}`,`Teaching heuristic ${score}/100. ${m.alignment<70?'Next: snap edges to the grid.':'Next: check whether the main chart is prominent enough.'}`)};
    b.controls.querySelector('#labXray').onchange=e=>{xray=e.target.checked;update()};b.controls.querySelector('#messLab').onclick=()=>{cards.forEach((d,i)=>{d.x+=i%2?19:-13;d.y+=(i%3-1)*13});update()};b.controls.querySelector('#resetLab').onclick=()=>{cards.forEach((d,i)=>Object.assign(d,initial[i]));update()};update()}
  function demoLab(s){demoLabCore(s,false)}function demoXray(s){demoLabCore(s,true)}

  function demoMultiscreen(section){let zoom=100;const b=demoBase(section,range('multiZoom',lang==='zh'?'文字缩放':'Text zoom',100,200,zoom,10)+`<p style="font-size:.78rem;color:var(--muted)">${lang==='zh'?'一套内容模型，同时生成桌面、平板和手机视图。':'One content model generates desktop, tablet, and mobile views.'}</p>`);const svg=b.svg;const screens=[{name:'DESKTOP',w:1180,x:24,drawW:315},{name:'TABLET',w:768,x:354,drawW:190},{name:'MOBILE',w:375,x:563,drawW:135}];const update=()=>{svg.selectAll('*').remove();screens.forEach(s=>{const scale=s.drawW/s.w,frameH=350;svg.append('rect').attr('x',s.x).attr('y',52).attr('width',s.drawW).attr('height',frameH).attr('rx',8).attr('fill','#fff').attr('stroke','#cfd6e5');svg.append('text').attr('class','svg-meta').attr('x',s.x).attr('y',35).text(`${s.name} · ${s.w}px`);const g=svg.append('g').attr('transform',`translate(${s.x},62) scale(${scale})`);const cards=layoutForWidth(s.w,true).map(d=>({...d,y:d.y*(zoom/100),h:d.h*(zoom/100)}));const cg=g.selectAll('g').data(cards,d=>d.id).join('g').attr('transform',d=>`translate(${d.x},${d.y})`);cg.append('rect').attr('class','svg-card').attr('width',d=>d.w).attr('height',d=>d.h).attr('rx',6/scale);cg.append('text').attr('class','svg-label').attr('x',10).attr('y',20).attr('font-size',Math.max(10,11/scale)).text(d=>nameOf(d.id))});setStatus(b,zoom>160?'200% 附近开始暴露固定高度与信息折叠风险。':'三种视图共享模块身份，只改变顺序、列数与尺寸。',zoom>160?'Near 200%, fixed heights and disclosure risks become visible.':'All three views share module identity; only order, columns, and size change.')};const el=b.controls.querySelector('#multiZoom');el.oninput=()=>{zoom=+el.value;b.controls.querySelector('#multiZoomOut').textContent=`${zoom}%`;update()};b.controls.querySelector('#multiZoomOut').textContent=`${zoom}%`;update()}

  renderApp();
})();
